### ISSUE TITLE
`make all` Ruby Error

### ISSUE THREAD

**Issue by fishcharlie** [vapor/benchmarks#4]
#3 fixed my problem with Go. Thanks so much for that fix.

However, I'm now getting this error with Ruby when running `make all`:

```
 => ERROR [4/4] RUN bundle install                                                                                                     0.3s
------
 > [4/4] RUN bundle install:
0.293 Your Ruby version is 3.2.2, but your Gemfile specified 2.5.1
------
Dockerfile:7
--------------------
   5 |     COPY . .
   6 |
   7 | >>> RUN bundle install
   8 |
   9 |     CMD ["bin/rails", "s", "-b", "0.0.0.0", "-p", "9000", "-e", "production"]
--------------------
ERROR: failed to solve: process "/bin/sh -c bundle install" did not complete successfully: exit code: 18
make: *** [rails] Error 1
```

**Comment by 0xTim** [comment]
@fishcharlie that's because you're running a newer version than required. You can fix that with `rbenv` or installing the required version of Ruby. Having said that, this repo is _very_ old, unmaintained and testing very old versions of Vapor so will be archived soon
